/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicalstore;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class SellingReport1 extends javax.swing.JInternalFrame {

	JPanel p;
	JScrollPane sc;
	Connection con;
	Statement st;
	ResultSetMetaData rm;
	ResultSet rs;
	String column[];
	DefaultTableModel dm;
	int col,count;
        boolean flag=true,flag1=true;
        String query=null;
    /**
     * Creates new form BillReport1
     */
    public SellingReport1() {
        setVisible(true);
        
        initComponents();
        dm=new DefaultTableModel();
        tb.setEnabled(false);
        
        try{
            Class.forName("org.apache.derby.jdbc.ClientDriver");
		con=DriverManager.getConnection("jdbc:derby://localhost:1527/MedicalStore","aa","123");
		st=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,
                ResultSet.CONCUR_UPDATABLE);
        }
        catch(Exception e)
        {
            System.out.println("Connection not setup");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtstdate = new javax.swing.JTextField();
        txtenddate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(975, 450));

        jLabel1.setText("Name :");

        jLabel2.setText("Record Between :");

        jLabel3.setText("and");

        txtstdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtstdateFocusGained(evt);
            }
        });
        txtstdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdateActionPerformed(evt);
            }
        });

        txtenddate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtenddateFocusGained(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Show All Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb);

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Date:");

        txtdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdateFocusGained(evt);
            }
        });
        txtdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtdateMouseEntered(evt);
            }
        });
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });

        jLabel5.setText("(yyyy-mm-dd)");

        jLabel6.setText("(yyyy-mm-dd)");

        jLabel7.setText("(yyyy-mm-dd)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(33, 33, 33)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(169, 169, 169)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtstdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtenddate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)))))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtenddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         flag1=false;
         while(dm.getRowCount()>0)
        {
            for(int i=0;i<dm.getRowCount();i++)
            {
                dm.removeRow(i);
                
            }
            
        }
         jButton2.disable();
        
        try
		{
                
		
		rs=st.executeQuery("select * from bill");
                if(flag==true)
                { flag=false;
		rm=rs.getMetaData();
		col=rm.getColumnCount();
		column=new String[col];
                
                
		for(count=0;count<column.length;count++)
		{
		column[count]=rm.getColumnName(count+1);
		dm.addColumn(column[count]);
               
                }
                
		
                }
		while(rs.next())
		{
			
		dm.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10)});
                }
                
		tb.setModel(dm);
		
		
		}
		catch(Exception e)
		{
		System.out.println("Error in connectivity"+e);
		}
	        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       

        flag1=false;
        while(dm.getRowCount()>0)
        {
            for(int i=0;i<dm.getRowCount();i++)
            {
                dm.removeRow(i);
                
            }
            
        }
        jButton2.enable();
        
        
        
        try
		{
                 if(txtstdate.getText().equals("") && txtenddate.getText().equals(""))
                 {
                     String name=txtname.getText().trim();
                     String date=txtdate.getText().trim();
                     if(date.equals(""))
                     {
                     query="select * from bill where customer_name='"+name+"'";
                     }
                     else
                     {
                       query="select * from bill where customer_name='"+name+"'"+"and date='"+date+"'";   
                     }
                 }
                 
                 if(txtname.getText().equals("") && txtdate.getText().equals(""))
                 {
                     String stdate=txtstdate.getText().trim();
                     String enddate=txtenddate.getText().trim();
                     
                     if(stdate.equals(""))
                     {
                        query="select * from bill where date='"+enddate+"'"; 
                     }
                     else if(enddate.equals(""))
                     {
                        query="select * from bill where date='"+stdate+"'"; 
                     }
                     else
                     {
                        query="select * from bill where date between '"+stdate+"'"+" and '"+enddate+"'"; 
                     }
                 }
                 if(txtdate.getText().equals("") && txtname.getText().isEmpty()==false && txtstdate.getText().isEmpty()==false && txtenddate.getText().isEmpty()==false)
                 {
                     String name=txtname.getText().trim();
                     String stdate=txtstdate.getText().trim();
                     String enddate=txtenddate.getText().trim();
                     query="select * from bill where customer_name='"+name+"'"+"and date between '"+stdate+"'"+" and '"+enddate+"'"; ;
                 }
                 if(txtdate.getText().isEmpty()==false && txtname.getText().isEmpty()==false && txtstdate.getText().isEmpty()==false && txtenddate.getText().isEmpty()==false)
                 {
                     JOptionPane.showMessageDialog(null,"Either Enter Name and Date  or   Record Between   or   Name and Record Between");
                
                 }
                 
                 
                 
                 rs=st.executeQuery(query);
		
                if(flag==true)
                {flag=false;
		rm=rs.getMetaData();
		col=rm.getColumnCount();
		column=new String[col];
		for(count=0;count<column.length;count++)
		{
		column[count]=rm.getColumnName(count+1);
                
       		dm.addColumn(column[count]);
                
                }
		}
		while(rs.next())
		{
			
		dm.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10)});
                }
                
		tb.setModel(dm);
                 
	
		}
		catch(Exception e)
		{
		System.out.println("Error in connectivity"+e);
		}
        txtname.setText("");
        txtdate.setText("");
        txtstdate.setText("");
        txtenddate.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            
        if(flag1==false)
        {
        try {
                
                st.close();
                rs.close();
                
            } catch (SQLException ex) {
                Logger.getLogger(SellingReport1.class.getName()).log(Level.SEVERE, null, ex);
            }
                    
        this.dispose();  
        }
        else 
         this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void txtdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateMouseEntered

    private void txtdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdateFocusGained
         // TODO add your handling code here:
    }//GEN-LAST:event_txtdateFocusGained

    private void txtstdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstdateFocusGained
       // TODO add your handling code here:
    }//GEN-LAST:event_txtstdateFocusGained

    private void txtenddateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtenddateFocusGained
       // TODO add your handling code here:
    }//GEN-LAST:event_txtenddateFocusGained

    private void txtstdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtenddate;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtstdate;
    // End of variables declaration//GEN-END:variables
}
